FROM golang:alpine AS build

WORKDIR /opt
# Install prerequisites
RUN apk add --no-cache git make

RUN git clone https://github.com/cbeuw/Cloak.git

# Set up Go module and add dependencies
WORKDIR /opt/Cloak

RUN go mod tidy

RUN make server

FROM alpine:latest

RUN apk upgrade --no-cache && \
    apk add --no-cache tzdata && \
    rm -rf /var/cache/apk/*


# WORKDIR /app
# COPY --from=build /opt/Cloak/build/ck-server /app/ck-server
# COPY cloak-server.conf /app/config.json
# COPY entrypoint-cloak-server.sh /app/entrypoint.sh
# RUN chmod +x /app/ck-server
# RUN chmod +x /app/entrypoint.sh

# ENTRYPOINT ["/app/entrypoint.sh"]
# CMD ["/app/ck-server", "-c", "/app/config.json"]

