FROM golang:alpine AS build

WORKDIR /opt
# Install prerequisites
RUN apk add --no-cache git make

RUN git clone https://github.com/cbeuw/Cloak.git
RUN git describe --tags $(git rev-list --tags --max-count=1) > version.txt

# Set up Go module and add dependencies
WORKDIR /opt/Cloak

RUN go mod tidy

RUN make server

FROM alpine:latest

RUN apk upgrade --no-cache && \
    apk add --no-cache tzdata && \
    rm -rf /var/cache/apk/*

WORKDIR /app
COPY --from=build /opt/Cloak/build/ck-server /app/ck-server



LABEL org.opencontainers.image.source=https://github.com/DobbyVPN/dobbyvpn-server
LABEL org.opencontainers.image.version=$(cat version.txt)

